/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package otel_oto_java;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class oda extends javax.swing.JFrame {
    ResultSet result,result1,result2,result3;
    Connection connection = null;
    Statement statement,statement1,statement2,statement3 ;
    int sutunSayisi,sutunSayisi1,sutunSayisi2,sutunSayisi3 ;
    public oda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        odano = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        odakat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ytks = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        odaucret = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(43, 242, 43));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 204, 0)));

        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setText("Oda No : ");

        jLabel2.setText("Oda Kat : ");

        jLabel3.setText("Yatak Sayısı : ");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(0, 102, 0));
        jButton1.setText("✓ Güncelle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Oda Güncelleme");

        jLabel6.setText("Oda Tur :");

        jComboBox1.setEditable(true);
        jComboBox1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tek Kişilik", "Çift Kişilik", "V.I.P (Tek Kişilik)", "V.I.P (Çift Kişilik)", "King Suit", "Ekonomik Oda(5 Kişilik)" }));

        jLabel7.setText("Oda Ücret :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(144, 144, 144))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(odakat, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ytks, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(odano, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(odaucret, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(odano, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(odakat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ytks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(86, 86, 86))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(odaucret, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(37, 37, 37))))
        );

        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("←");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(102, 255, 102));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Oda No", "Ad", "Soyad", "Oda No"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setBackground(new java.awt.Color(102, 255, 102));
        jTable2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Oda No", "Ad", "Soyad", "Oda No"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton3.setText("Tümünü Listele");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Ara");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(298, 298, 298)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jButton4)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addGap(118, 118, 118)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
int oda_noo=0;String oda_tur=" ";
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        oda_noo = Integer.valueOf(odano.getText());
        int oda_kat = Integer.valueOf(odakat.getText());
        int oda_ytks = Integer.valueOf(ytks.getText());
        
        Object oda_turob = jComboBox1.getSelectedItem();
        oda_tur = String.valueOf(oda_turob);
        
        int oda_ucret = Integer.valueOf(odaucret.getText());
        
        Oda_U update = new Oda_U();
        int s = Duruma_Gore(oda_noo);
            if (s!=0) {
            update.guncelle(oda_noo, oda_kat, oda_ytks, oda_tur,oda_ucret);
            }
        Tekli_Listele(oda_noo);   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       Listele();
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        menu m1= new menu();
        m1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       Listele();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int  oda_noara = Integer.valueOf(jTextField1.getText());
        Tekli_Listele(oda_noara); 
    }//GEN-LAST:event_jButton4ActionPerformed
//    GİRİLEN ODANIN VERİTABANINDA OLUP OLMADIĞINA BAKAR
    int Duruma_Gore(int s)
    {
    try {
      Class.forName("com.mysql.jdbc.Driver");
              // bağlantı kuruyoruz. 
      connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/otel_rezervasyon?zeroDateTimeBehavior=convertToNull","root","");
    
      statement=connection.createStatement();

      int oda_no =s;
       int q=0;
      result=statement.executeQuery("Select oda_no from oda_bilgileri");
      sutunSayisi=result.getMetaData().getColumnCount();
       while(result.next()){
               for(int i=1;i<=sutunSayisi;i++)
                   if (oda_no==Integer.valueOf(result.getObject(i).toString())) {
                       q++;
                   }
         }
       if (q==0) {
        JOptionPane.showMessageDialog(null,"Böyle bir oda yok!");
        result.close();
        connection.close();
    }
        return 1;
    }
    catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "VeriTabani Baglanti Hatasi");
        return 0;
    }
    }  
  
  void Tekli_Listele(int s)
    {
    try {
      Class.forName("com.mysql.jdbc.Driver");

   // Oluşturduğumuz veritabanının adını,kullanıcı adı ve şifreyi göndip Mysql                 // bağlantı kuruyoruz. 
      connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/otel_rezervasyon?zeroDateTimeBehavior=convertToNull","root","");

     // bağlantı tipinden statement oluşturuyoruz.      
      statement=connection.createStatement();
      statement1=connection.createStatement();
      statement2=connection.createStatement();
     // kişiler tablosundaki tum verileri alıyoruz 
     
     DefaultTableModel table=new DefaultTableModel();
     
      result=statement.executeQuery("Select * from oda_bilgileri where oda_no ="+s);
      
      sutunSayisi=result.getMetaData().getColumnCount();
      
      for(int i=1;i<=sutunSayisi;i++)
            table.addColumn(result.getMetaData().getColumnName(i));
      
      
      Object[] row2=new Object[1];
      while(result.next()){
        row2[0] = result.getObject(4);
        Object[] row=new Object[sutunSayisi];
        for(int i=1;i<=sutunSayisi;i++)
            row[i-1]=result.getObject(i);
        table.addRow(row);
      }
      
      String idstr = String.valueOf(row2[0]);
      int id = Integer.valueOf(idstr); 
      result1=statement1.executeQuery("Select * from odatip where oda_tipID = "+id);
      
      //Veri tabanındaki sutunlarin sayisini alıyoruz.
       
       sutunSayisi1=result1.getMetaData().getColumnCount();

      //Veri tabanındaki sutunlarin sayisini alıyoruz.
      
       //Table tipinde model olusturuyoruz.
        
        DefaultTableModel table1=new DefaultTableModel();
      

       //table referansına veritabanındaki sutunları ekliyoruz.
        
        for(int i=1;i<=sutunSayisi1;i++)
            table1.addColumn(result1.getMetaData().getColumnName(i));
        
     
       //Veritabanindaki tum satir ve sutunlari tarayip Table'a ekliyoruz.
         
        while(result1.next()){
              Object[] row1=new Object[sutunSayisi];
               for(int i=1;i<=sutunSayisi1;i++)
                  row1[i-1]=result1.getObject(i);
              table1.addRow(row1);
         }

         jTable1.setModel(table);
         jTable2.setModel(table1);

       //baglantıları kapatıyoruz.
        result.close();
        result1.close();
        connection.close();
      
    }
    catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "VeriTabani Baglanti Hatasi");
       
    }
    } 
    void Listele()
    {
    try {
      Class.forName("com.mysql.jdbc.Driver");

   // Oluşturduğumuz veritabanının adını,kullanıcı adı ve şifreyi göndip Mysql                 // bağlantı kuruyoruz. 
      connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/otel_rezervasyon?zeroDateTimeBehavior=convertToNull","root","");

     // bağlantı tipinden statement oluşturuyoruz.      
      statement=connection.createStatement();
      statement1=connection.createStatement();
     // kişiler tablosundaki tum verileri alıyoruz  
      result=statement.executeQuery("Select * from oda_bilgileri ");
      
      //Veri tabanındaki sutunlarin sayisini alıyoruz.
       sutunSayisi=result.getMetaData().getColumnCount();
       
       result1=statement1.executeQuery("Select * from odatip ");

      //Veri tabanındaki sutunlarin sayisini alıyoruz.
       sutunSayisi1=result1.getMetaData().getColumnCount();
       //Table tipinde model olusturuyoruz.
        DefaultTableModel table=new DefaultTableModel();
        DefaultTableModel table1=new DefaultTableModel();

       //table referansına veritabanındaki sutunları ekliyoruz.
        for(int i=1;i<=sutunSayisi;i++)
            table.addColumn(result.getMetaData().getColumnName(i));
         for(int i=1;i<=sutunSayisi1;i++)
            table1.addColumn(result1.getMetaData().getColumnName(i));
     
       //Veritabanindaki tum satir ve sutunlari tarayip Table'a ekliyoruz.
         while(result.next()){
              Object[] row=new Object[sutunSayisi];
               for(int i=1;i<=sutunSayisi;i++)
                  row[i-1]=result.getObject(i);
              table.addRow(row);
         }
         while(result1.next()){
              Object[] row1=new Object[sutunSayisi1];
               for(int i=1;i<=sutunSayisi1;i++)
                  row1[i-1]=result1.getObject(i);
              table1.addRow(row1);
         }

        
         jTable2.setModel(table1);
         jTable1.setModel(table);

       //baglantıları kapatıyoruz.
        result.close();
        result1.close();
        connection.close();
    }
    catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "VeriTabani Baglanti Hatasi");
    }
    }  
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new oda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField odakat;
    private javax.swing.JTextField odano;
    private javax.swing.JTextField odaucret;
    private javax.swing.JTextField ytks;
    // End of variables declaration//GEN-END:variables
}
